# Generated by Django 5.2.9 on 2025-12-14 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomeBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('image', models.ImageField(upload_to='banners/', verbose_name='تصویر')),
                ('url', models.URLField(max_length=500, verbose_name='لینک مقصد')),
                ('position', models.CharField(choices=[('top_right', 'بالا راست (کنار اسلایدر)'), ('top_left', 'بالا چپ (کنار اسلایدر)'), ('mid_two', 'میانه (۲ تایی)'), ('bottom_four', 'پایین (۴ تایی)')], max_length=20, verbose_name='موقعیت نمایش')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
            ],
            options={
                'verbose_name': 'بنر تبلیغاتی',
                'verbose_name_plural': 'بنرهای تبلیغاتی',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('sub_title', models.CharField(blank=True, max_length=100, null=True, verbose_name='زیرعنوان')),
                ('image', models.ImageField(upload_to='sliders/', verbose_name='تصویر (1920x600)')),
                ('url', models.URLField(max_length=500, verbose_name='لینک مقصد')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'اسلایدر',
                'verbose_name_plural': 'اسلایدرها',
            },
        ),
    ]
