# Generated by Django 5.2.9 on 2025-12-13 12:09

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_address'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'ordering': ['-created_at'], 'verbose_name': 'آدرس', 'verbose_name_plural': 'آدرس\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'کاربر', 'verbose_name_plural': 'کاربرها'},
        ),
        migrations.AlterModelOptions(
            name='vendor',
            options={'verbose_name': 'فروشنده', 'verbose_name_plural': 'فروشنده ها'},
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(max_length=50, verbose_name='شهر'),
        ),
        migrations.AlterField(
            model_name='address',
            name='full_address',
            field=models.TextField(verbose_name='آدرس کامل'),
        ),
        migrations.AlterField(
            model_name='address',
            name='phone_number',
            field=models.CharField(max_length=15, verbose_name='شماره تماس'),
        ),
        migrations.AlterField(
            model_name='address',
            name='postal_code',
            field=models.CharField(max_length=10, verbose_name='کد پستی'),
        ),
        migrations.AlterField(
            model_name='address',
            name='province',
            field=models.CharField(max_length=50, verbose_name='استان'),
        ),
        migrations.AlterField(
            model_name='address',
            name='recipient_name',
            field=models.CharField(max_length=100, verbose_name='نام گیرنده'),
        ),
        migrations.AlterField(
            model_name='address',
            name='title',
            field=models.CharField(help_text='مثال: خانه، محل کار', max_length=50, verbose_name='عنوان آدرس'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='ایمیل'),
        ),
        migrations.AlterField(
            model_name='user',
            name='full_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='نام و نام خانوادگی'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '09123456789'.", regex='^09\\d{9}$')], verbose_name='شماره موبایل'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='commission_rate',
            field=models.DecimalField(decimal_places=1, default=5.0, help_text='درصد فروش انجام شده توسط پلتفرم', max_digits=4, verbose_name='نرخ کمیسیون (%)'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='vendor_covers/', verbose_name='تصویر کاور'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='description',
            field=models.TextField(blank=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='vendor_logos/', verbose_name='لوگو'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='slug',
            field=models.SlugField(allow_unicode=True, max_length=150, unique=True, verbose_name='اسلاگ'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='status',
            field=models.CharField(choices=[('pending', 'در انتظار تأیید'), ('active', 'فعال'), ('suspended', 'توقف فعالیت')], default='pending', max_length=10, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='store_name',
            field=models.CharField(max_length=100, unique=True, verbose_name='نام فروشگاه'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_profile', to=settings.AUTH_USER_MODEL, verbose_name='مالک'),
        ),
    ]
