# Generated by Django 5.2.9 on 2025-12-13 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_category_options_category_level_category_lft_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MegaMenuColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='مثال: بر اساس برند، بر اساس کاربری', max_length=100, verbose_name='عنوان ستون')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_columns', to='products.category', verbose_name='نمایش در دسته')),
            ],
            options={
                'verbose_name': 'ستون مگا\u200cمنو',
                'verbose_name_plural': 'ستون\u200cهای مگا\u200cمنو',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='MegaMenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='مثال: لپ\u200cتاپ گیمینگ، سری Zenbook', max_length=100, verbose_name='عنوان لینک')),
                ('url', models.CharField(help_text='مثال: /products/laptop/?brand=asus یا /products/laptop/?usage=gaming', max_length=500, verbose_name='لینک مقصد')),
                ('image', models.ImageField(blank=True, null=True, upload_to='menu_icons/', verbose_name='آیکون')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
                ('column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='products.megamenucolumn', verbose_name='ستون والد')),
            ],
            options={
                'verbose_name': 'آیتم منو',
                'verbose_name_plural': 'آیتم\u200cهای منو',
                'ordering': ['order'],
            },
        ),
    ]
