# Generated by Django 5.2.9 on 2025-12-13 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_megamenucolumn_megamenuitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productattribute',
            options={'ordering': ['order'], 'verbose_name': 'ویژگی محصول', 'verbose_name_plural': 'ویژگی\u200cهای محصولات'},
        ),
        migrations.RemoveField(
            model_name='productattribute',
            name='category',
        ),
        migrations.AddField(
            model_name='productattribute',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='ترتیب'),
        ),
        migrations.AlterField(
            model_name='productattribute',
            name='key',
            field=models.CharField(help_text='مثال: ram', max_length=50, verbose_name='نام ویژگی (انگلیسی)'),
        ),
        migrations.AlterField(
            model_name='productattribute',
            name='label',
            field=models.CharField(help_text='مثال: حافظه رم', max_length=50, verbose_name='عنوان نمایشی (فارسی)'),
        ),
        migrations.CreateModel(
            name='AttributeGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='مثال: مشخصات کلی، صفحه نمایش، پردازنده', max_length=100, verbose_name='نام گروه')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute_groups', to='products.category', verbose_name='دسته\u200cبندی')),
            ],
            options={
                'verbose_name': 'گروه ویژگی',
                'verbose_name_plural': 'گروه\u200cهای ویژگی',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='productattribute',
            name='group',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='products.attributegroup', verbose_name='گروه والد'),
            preserve_default=False,
        ),
    ]
