# Generated by Django 5.2.9 on 2025-12-14 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_productattribute_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productattribute',
            name='is_main',
            field=models.BooleanField(default=False, verbose_name='نمایش در ویژگی\u200cهای اصلی'),
        ),
    ]
