# Generated by Django 5.2.9 on 2025-12-14 20:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_productattribute_is_main'),
    ]

    operations = [
        migrations.AddField(
            model_name='productattribute',
            name='is_filterable',
            field=models.BooleanField(default=False, verbose_name='استفاده به عنوان فیلتر'),
        ),
        migrations.AlterField(
            model_name='productattribute',
            name='key',
            field=models.CharField(help_text='فقط حروف انگلیسی کوچک و _ مجاز است. مثال: screen_size', max_length=50, validators=[django.core.validators.RegexValidator(message='نام ویژگی فقط می\u200cتواند شامل حروف کوچک انگلیسی، اعداد و خط زیر (_) باشد. فاصله مجاز نیست.', regex='^[a-z0-9_]+$')], verbose_name='نام ویژگی (انگلیسی)'),
        ),
    ]
