# Generated by Django 5.2.9 on 2025-12-14 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_productattribute_is_filterable_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_special',
            field=models.BooleanField(default=False, verbose_name='پیشنهاد شگفت\u200cانگیز (ویژه)'),
        ),
    ]
