# Generated by Django 5.2.9 on 2025-12-16 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_product_is_special'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_comparison_root',
            field=models.BooleanField(default=False, help_text="اگر این تیک را بزنید، تمام محصولات موجود در زیرمجموعه\u200cهای این دسته می\u200cتوانند با هم مقایسه شوند. (مثلاً برای دسته 'موبایل' تیک بزنید تا سامسونگ و اپل مقایسه شوند)", verbose_name='اجازه مقایسه زیرمجموعه\u200cها'),
        ),
    ]
