# Generated by Django 5.2.9 on 2025-12-22 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_alter_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='model_name',
            field=models.CharField(default='', help_text='مثال: Galaxy S25 Ultra', max_length=100, verbose_name='مدل محصول'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='title_desc',
            field=models.CharField(blank=True, help_text='مثال: ظرفیت 256 گیگابایت با رم 12', max_length=255, verbose_name='مشخصات کلیدی در عنوان'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(blank=True, max_length=255, verbose_name='نام کامل محصول (تولید خودکار)'),
        ),
    ]
